server:
  port: 8082

spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.9.128:9092
    consumer:
      bootstrap-servers: 192.168.9.128:9092
      group-id: consumer-group-1
    client-id: kafka-client-1
esa:
  host: 192.168.9.128
  port: 9200
  scheme: http
  index: test_index